theme: minima
title: My Coding Journey
author: Tyler Van Nostrand
email: tvannost32@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is where I will write all about my journey into learning to code. It will include how I came to my decision to learn how,
  and through the process of me learning.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
